asv-soft/asv-avalonia

src/Asv.Avalonia/Shell/View/DockControl.axaml.cs
Asana: https://app.asana.com/0/1203851531040615/1209374768300103
=> fix(dock-control): refactor on pressed ivent to better work with tabs and map

src/Asv.Avalonia/Controls/ContentDialog/ContentDialog.cs, src/Asv.Avalonia/Controls/ContentDialog/ContentDialog.properties.cs, src/Asv.Avalonia/Controls/ContentDialog/Deferral.cs, src/Asv.Avalonia/Controls/ContentDialog/EventArgs/ContentDialogButtonClickEventArgs.cs, src/Asv.Avalonia/Controls/ContentDialog/EventArgs/ContentDialogClosingEventArgs.cs, src/Asv.Avalonia/Services/Dialogs/DialogService.cs
#patch 2
Asana: https://app.asana.com/0/1203851531040615/1209429665199687
=> fix: add ContentDialog

src/Asv.Avalonia.Map/Controls/Canvas/AnnotationLayer.cs, src/Asv.Avalonia.Map/Tools/PointExtensions.cs, src/Asv.Avalonia/Asv.Avalonia.csproj.DotSettings, src/Asv.Avalonia/Controls/Workspace/WorkspacePanel.cs, src/Asv.Avalonia/Shell/DesktopShellViewModel.cs, src/Asv.Avalonia/Shell/IShell.cs, src/Asv.Avalonia/ViewModel/Routable/NavigationId.cs, src/Asv.Avalonia/ViewModel/Routable/NavigationPath.cs
Translate all comments from Russian to English.
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1209676923721122?focus=true
=> fix(asv-avalonia): translate comments

src/Asv.Avalonia/Converters/VersionConverter.cs
Implement ConvertBack method to return the original value if it is a string Asana: https://app.asana.com/0/1203851531040615/1209709385577011/f
=> fix(asv-avalonia): implement ConvertBack

src/Asv.Avalonia.DC/Asv.Avalonia.DC.csproj, src/Asv.Avalonia.Map/Asv.Avalonia.Map.csproj, src/Asv.Avalonia.Map/Cache/FileSystem/FileSystemCache.cs, src/Asv.Avalonia.Map/Cache/Memory/MemoryTileCache.cs, src/Asv.Avalonia.Map/Cache/TileCache.cs, src/Asv.Avalonia.Map/Cache/TileKey.cs, src/Asv.Avalonia.Map/Controls/Background/MapBackground.cs, src/Asv.Avalonia.Map/Controls/Canvas/AnnotationLayer.cs, src/Asv.Avalonia.Map/Controls/Canvas/HorizontalOffset.cs, src/Asv.Avalonia.Map/Controls/Canvas/MapCanvas.cs, src/Asv.Avalonia.Map/Controls/Canvas/PolygonLayer.cs, src/Asv.Avalonia.Map/Controls/Canvas/VerticalOffset.cs, src/Asv.Avalonia.Map/Controls/ItemsControl/MapItem.axaml.cs, src/Asv.Avalonia.Map/Controls/ItemsControl/MapItemsControl.axaml.cs, src/Asv.Avalonia.Map/Loader/TileLoader.cs, src/Asv.Avalonia.Map/Providers/Projection/IMapProjection.cs, src/Asv.Avalonia.Map/Tools/GeoPointExtension.cs, src/Asv.Avalonia.Map/Tools/PointExtensions.cs
Enhance Husky configuration and fix errors after enabling it Asana: https://app.asana.com/0/1203851531040615/1209709314147227/f
=> feat (asv-avalonia): supplement husky

src/Asv.Avalonia.Example/Asv.Avalonia.Example.csproj.DotSettings, src/Asv.Avalonia.Example/Pages/TestInfoBox/Commands/OpenTestInfoBoxPage.cs, src/Asv.Avalonia.Example/Pages/TestInfoBox/HomePageTesInfoBoxExtension.cs, src/Asv.Avalonia.Example/Pages/TestInfoBox/TestInfoBoxPageView.axaml, src/Asv.Avalonia.Example/Pages/TestInfoBox/TestInfoBoxPageView.axaml.cs, src/Asv.Avalonia.Example/Pages/TestInfoBox/TestInfoBoxPageViewModel.cs, src/Asv.Avalonia/Asv.Avalonia.csproj, src/Asv.Avalonia/Asv.Avalonia.csproj.DotSettings, src/Asv.Avalonia/Controls/ContentDialog/ContentDialog.properties.cs, src/Asv.Avalonia/Controls/InfoBar/InfoBar.cs, src/Asv.Avalonia/Controls/InfoBar/InfoBar.properties.cs, src/Asv.Avalonia/Controls/InfoBar/InfoBarClosedEventArgs.cs, src/Asv.Avalonia/Controls/InfoBar/InfoBarClosingEventArgs.cs, src/Asv.Avalonia/Controls/InfoBar/InfoBarEnums.cs, src/Asv.Avalonia/Controls/InfoBar/InfoBarPanel.cs, src/Asv.Avalonia/Controls/InfoBar/InfoBarPanel.properties.cs, src/Asv.Avalonia/Controls/InfoBar/InfoBarStyles.axaml, src/Asv.Avalonia/Controls/InfoBar/ThicknessExtension.cs, src/Asv.Avalonia/Controls/TypedEventHandler.cs, src/Asv.Avalonia/Shell/Pages/Plugins/Installed/InstalledPluginsView.axaml, src/Asv.Avalonia/Shell/Pages/Plugins/Market/PluginsMarketView.axaml, src/Asv.Avalonia/Theme.axaml, src/Asv.Avalonia/Tools/PseudoClassesHelper.cs
Remove FA dependencies
Asana: https://app.asana.com/0/1203851531040615/1209709315665833/f
=> feat: add InfoBar control from FA

src/Asv.Avalonia/Shell/ShellView.axaml, src/Asv.Avalonia/Shell/View/DockControl.axaml, src/Asv.Avalonia/Shell/View/DockControl.axaml.cs
Asana: https://app.asana.com/0/1206009821057985/1209579100034480
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1209606080092569
- https://app.asana.com/0/0/1209676923721128
=> fix(dock): fix SelectedItem when open new tab. fixed unspliting tabs after close.

src/Asv.Avalonia.DC/Asv.Avalonia.DC.csproj, src/Asv.Avalonia.Example.Api/Asv.Avalonia.Example.Api.csproj, src/Asv.Avalonia.Example.Desktop/Asv.Avalonia.Example.Desktop.csproj, src/Asv.Avalonia.Example.Plugin.PluginExample/Asv.Avalonia.Example.Plugin.PluginExample.csproj, src/Asv.Avalonia.Example.Plugin.PluginExample/Asv.Avalonia.Example.Plugin.PluginExample.csproj.DotSettings, src/Asv.Avalonia.Example/Asv.Avalonia.Example.csproj, src/Asv.Avalonia.Example/Pages/Flight/Widgets/UavWidgetViewModel.cs, src/Asv.Avalonia.IO/Asv.Avalonia.IO.csproj, src/Asv.Avalonia.IO/Commands/ProtocolPortCommand.cs, src/Asv.Avalonia.IO/Pages/Settings/Connections/PortViewModel.cs, src/Asv.Avalonia.IO/Pages/Settings/Connections/SerialPort/SerialPortViewModel.cs, src/Asv.Avalonia.IO/Pages/Settings/Connections/SettingsConnectionViewModel.cs, src/Asv.Avalonia.IO/Services/DeviceManager.cs, src/Asv.Avalonia.Map/Asv.Avalonia.Map.csproj, src/Asv.Avalonia.Plugins/Asv.Avalonia.Plugins.csproj, src/Asv.Avalonia/Asv.Avalonia.csproj, src/Directory.Build.props
feat: update nugets for the code analyzers and add code style checks for all the projects
=> feat: update asv.common version

src/Asv.Avalonia/Shell/DesktopShellViewModel.cs, src/Asv.Avalonia/Shell/Window/ShellWindow.axaml.cs
Move window state related properties and methods to DesktopShellViewModel Asana: https://app.asana.com/0/1203851531040615/1209696774500284/f
=> fix(asv-avalonia): bug window state

src/Asv.Avalonia.Example/Pages/Flight/Widgets/UavWidget/MissionProgress/MissionProgressViewModel.cs, src/Asv.Avalonia/Shell/DesktopShellViewModel.cs, src/Asv.Avalonia/Shell/Window/ShellWindow.axaml.cs
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1209975643618856?focus=true
=> fix: add check of mission items count before calling for the first item

src/Asv.Avalonia/Theme.axaml
Asana: https://app.asana.com/1/1200746044236722/project/1206009821057985/task/1210001258894163?focus=true
=> fix(theme): enable redo/undo for ContentDialog textboxes

src/Asv.Avalonia.Example/Pages/Flight/Anchors/UavAnchor.cs
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1209978872391636?focus=true
=> fix: make polygon between home and current uav position properly redraw

src/Asv.Avalonia/Controls/TreePage/TreePageView.axaml
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1209853790787022?focus=true
=> fix(asv-avalonia): correct data type error

src/Asv.Avalonia/RS.Designer.cs, src/Asv.Avalonia/RS.resx, src/Asv.Avalonia/RS.ru.resx, src/Asv.Avalonia/Services/UnitService/Units/Altitude/FeetAltitudeUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/AmplitudeModulation/PercentAmplitudeModulationUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/DdmGp/MicroAmpDdmGpUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/DdmGp/MicroAmpRuDdmGpUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/DdmGp/PercentDdmGpUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/DdmLlz/MicroAmpDdmLlzUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/DdmLlz/MicroAmpRuDdmLlzUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/DdmLlz/PercentDdmLlzUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/Frequency/GigahertzFrequencyUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/Frequency/MegahertzFrequencyUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/Progress/InPartsProgressUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/Progress/PercentProgressUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/Sdm/PercentSdmBase.cs
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210011321744212?focus=true
=> fix: change unit item multipliers to the proper ones

src/Asv.Avalonia/Commands/ChangeCurrentUnitItemCommand.cs, src/Asv.Avalonia/Commands/OpenSettingsCommand.cs, src/Asv.Avalonia/Controls/TreePage/TreePageViewModel.cs, src/Asv.Avalonia/Services/Navigation/NavigationService.cs, src/Asv.Avalonia/Shell/Pages/PageViewModel.cs, src/Asv.Avalonia/Shell/Pages/Settings/Units/MeasureUnitViewModel.cs, src/Asv.Avalonia/Shell/Pages/Settings/Units/SettingsUnitsView.axaml, src/Asv.Avalonia/Shell/Pages/Settings/Units/SettingsUnitsViewModel.cs, src/Asv.Avalonia/Shell/ShellViewModel.cs, src/Asv.Avalonia/Shell/View/DockControl.axaml.cs
Asana: https://app.asana.com/1/1200746044236722/project/1206009821057985/task/1209768663122643?focus=true
=> feat(keymap): fix command for valid backup operation when undo/redo action with hotkeys

src/Asv.Avalonia.Example.Desktop/Program.cs, src/Asv.Avalonia/AppHost/Logging/LoggingMixin.cs, src/Asv.Avalonia/AppHost/SoloRun/SoloRunFeature.cs, src/Asv.Avalonia/AppHost/SoloRun/SoloRunFeatureMixin.cs, src/Asv.Avalonia/Services/LogService/LogService.cs, src/Directory.Build.props
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210629499999031?focus=true
=> fix: add logging to file

src/Asv.Avalonia/Asv.Avalonia.csproj.DotSettings, src/Asv.Avalonia/Controls/Dock/DockControl.axaml.cs, src/Asv.Avalonia/Controls/Dock/DockWindow.axaml.cs, src/Asv.Avalonia/Services/Cmd/Command/OpenPageCommandBase.cs, src/Directory.Build.props
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210658352355857?focus=true
=> fix: memorize windowed pages

src/Asv.Avalonia/Controls/Dock/DockControl.axaml.cs, src/Asv.Avalonia/Services/Navigation/NavigationService.cs, src/Asv.Avalonia/Shell/ShellViewModel.cs
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210629499999025?focus=true
=> feat: correct handle page selection and navigation when closing a page

src/Asv.Avalonia/Controls/AdaptiveTabControlStrip/AdaptiveTabStripTabControl.axaml, src/Asv.Avalonia/Controls/Dock/DockControl.axaml, src/Asv.Avalonia/Shell/Pages/Home/HomePageView.axaml, src/Asv.Avalonia/Shell/ShellView.axaml, src/Directory.Build.props
change the version of the app to 1.0.1
add placeholder for the bottom status field
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210509621120551?focus=true
=> fix: make Homepage items fit the smallest window size

src/Asv.Avalonia.DC/Asv.Avalonia.DC.csproj, src/Asv.Avalonia.Example.Android/Asv.Avalonia.Example.Android.csproj, src/Asv.Avalonia.Example.Api/Asv.Avalonia.Example.Api.csproj, src/Asv.Avalonia.Example.Desktop/Asv.Avalonia.Example.Desktop.csproj, src/Asv.Avalonia.Example.Plugin.PluginExample/Asv.Avalonia.Example.Plugin.PluginExample.csproj, src/Asv.Avalonia.Example.iOS/Asv.Avalonia.Example.iOS.csproj, src/Asv.Avalonia.Example/Asv.Avalonia.Example.csproj, src/Asv.Avalonia.GeoMap/Asv.Avalonia.GeoMap.csproj, src/Asv.Avalonia.IO/Asv.Avalonia.IO.csproj, src/Asv.Avalonia.Plugins/Asv.Avalonia.Plugins.csproj, src/Asv.Avalonia.Test/Asv.Avalonia.Test.csproj, src/Asv.Avalonia/Asv.Avalonia.csproj, src/Directory.Build.props
update all libs to the latest versions
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210902613481121?focus=true
=> feat: update project to dotnet core 9

src/Asv.Avalonia/Services/UnitService/Units/Frequency/GigahertzFrequencyUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/Frequency/KilohertzFrequencyUnit.cs, src/Asv.Avalonia/Services/UnitService/Units/Frequency/MegahertzFrequencyUnit.cs, src/Directory.Build.props
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210975594938370?focus=true
=> fix: change multipliers in Frequency unit items

src/Asv.Avalonia/Shell/Pages/Settings/Units/SettingsUnitsView.axaml, src/Asv.Avalonia/Shell/Pages/Settings/Units/SettingsUnitsViewModel.cs
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210866562209195?focus=true
=> feat: use SearchBoxView where possible

src/Asv.Avalonia/Asv.Avalonia.csproj.DotSettings, src/Asv.Avalonia/Controls/Items/ItemsList.cs, src/Asv.Avalonia/Controls/Items/ItemsListStyles.axaml, src/Asv.Avalonia/Controls/Tools/ToolsList.cs, src/Asv.Avalonia/Controls/Tools/ToolsListStyles.axaml, src/Asv.Avalonia/Shell/Pages/Home/HomePageView.axaml, src/Asv.Avalonia/Shell/Pages/Home/HomePageViewModel.cs, src/Asv.Avalonia/Styling/Theme.axaml
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1210886342818266
=> fix: home page layout

src/Directory.Build.props
Asana: https://app.asana.com/1/1200746044236722/project/1203851531040615/task/1211194034054324?focus=true
=> feat: update Asv.Common to v3.2.11-dev.2 and Asv.Mavlink to v4.0.18-dev.1

src/Asv.Avalonia/Controls/Dock/Window/DockWindow.axaml, src/Asv.Avalonia/Shell/ShellView.axaml
Asana: https://app.asana.com/1/1200746044236722/project/1210705292501615/task/1211160101974506
=> feat: remove focus on outside click
